### ISSUE TITLE
大佬，能否指导一下如何续期CK？

### ISSUE THREAD

**Issue by sclodestar** [IGuanggg/Very_Hunger#1]
如题，elmck很快就掉了，之前的续期CK脚本都无法用了，您这边还有什么办法续期吗？还望您不吝赐教。

**Comment by azehuihiu** [comment]
你是2400的本嘛

**Comment by sclodestar** [comment]
> 你是2400的本嘛

2400是什么的简称？是每天获取乐园币2400币的意思吗？

我拉取的是这位大佬的库，没看到续期的说明，不知道哪里可以续期，如果你知道的，还望告知一下，非常感谢

**Comment by IGuanggg** [comment]
自用库，没说明就是没这个，本人能力有限

**Comment by z6135** [comment]
开始查询最近的夺宝结果
网络链接失败，将在 2 秒后重试
网络异常，请检查网络状况
FAIL_SYS_ILLEGAL_ACCESS::非法请求
再延迟15秒就稳了
网络链接失败，将在 2 秒后重试
网络异常，请检查网络状况
FAIL_SYS_ILLEGAL_ACCESS::非法请求
TypeError: Cannot read properties of null (reading 'data')
    at _0x256459 (/ql/data/scripts/IGuanggg_Very_Hunger/ele_xydb.swap.js:13:96419)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x745918 (/ql/data/scripts/IGuanggg_Very_Hunger/ele_xydb.swap.js:13:97078)
    at async /ql/data/scripts/IGuanggg_Very_Hunger/ele_xydb.swap.js:13:110848

**Comment by z6135** [comment]
大佬部分脚本网络异常，需要什么签名吗，，，怎么联系

**Comment by IGuanggg** [comment]
> 大佬部分脚本网络异常，需要什么签名吗，，，怎么联系
就是坏了没了修

**Comment by z6135** [comment]
大佬，ck怎么购买！

**Comment by ngdikman** [comment]
大佬能分享下本地sign的镜像不？
